# Generated by Django 4.2.21 on 2025-05-17 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount in decimal', max_digits=10)),
                ('date', models.DateField(help_text='Date when payment was made')),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Check', 'Check'), ('Credit', 'Credit Card'), ('Bank', 'Bank Transfer')], help_text='Method used for payment', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional payment notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When payment record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When payment record was last updated')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='members.member')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='members.policy')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='payments.payment')),
            ],
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['member'], name='payments_pa_member__7b306c_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['date'], name='payments_pa_date_f2f1ad_idx'),
        ),
    ]
