# Generated by Django 4.2.21 on 2025-05-19 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_query', models.TextField(help_text='The original user query')),
                ('report_type', models.CharField(choices=[('claims', 'Claims Report'), ('commissions', 'Commissions Report'), ('lapses', 'Policy Lapses Report'), ('payments', 'Payments Report'), ('debit_orders', 'Debit Order Report')], max_length=50)),
                ('filters', models.JSONField(default=dict, help_text='JSON structure with filter parameters')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Query',
                'verbose_name_plural': 'Report Queries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('report_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_instances', to='reports_ai.reportquery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Report',
                'verbose_name_plural': 'Saved Reports',
                'ordering': ['-last_accessed'],
            },
        ),
        migrations.CreateModel(
            name='ReportExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('error', 'Error')], default='pending', max_length=20)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('execution_time', models.FloatField(blank=True, help_text='Execution time in seconds', null=True)),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('report_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='reports_ai.reportquery')),
            ],
            options={
                'verbose_name': 'Report Execution Log',
                'verbose_name_plural': 'Report Execution Logs',
                'ordering': ['-executed_at'],
            },
        ),
    ]
