# Generated by Django 5.2 on 2025-04-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('registration_no', models.CharField(max_length=100)),
                ('fsp_number', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('terms', models.TextField(blank=True)),
                ('debit_order_no', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=100)),
                ('branch_code', models.CharField(max_length=20)),
                ('account_no', models.CharField(max_length=50)),
                ('account_type', models.CharField(choices=[('Savings', 'Savings'), ('Current', 'Current')], max_length=50)),
            ],
        ),
    ]
