# Generated by Django 5.2 on 2025-04-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0003_plan_max_age_plan_min_age_plan_scheme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='underwriter',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
