# Generated by Django 5.2 on 2025-04-27 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0004_plan_modified_plan_underwriter'),
        ('settings_app', '0005_scheme_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='branch',
            field=models.ForeignKey(default=1, help_text='Which branch this scheme belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='schemes', to='settings_app.branch'),
            preserve_default=False,
        ),
    ]
