# Generated by Django 5.2 on 2025-05-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0005_scheme_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='prefix',
            field=models.CharField(blank=True, help_text='Short code like CHB-001', max_length=20, null=True),
        ),
    ]
