# Generated by Django 4.2.21 on 2025-05-13 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_delete_scheme'),
        ('schemes', '0006_scheme_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='branch',
            field=models.ForeignKey(help_text='Which branch this scheme belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='schemes', to='branches.branch'),
        ),
    ]
