# Generated by Django 4.2.21 on 2025-05-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0008_scheme_active_scheme_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='extra_email',
            field=models.EmailField(blank=True, help_text='Additional email address', max_length=254, null=True),
        ),
    ]
