# Generated by Django 4.2.21 on 2025-05-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0010_plan_admin_fee_plan_agent_commission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='lapse_period',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='plan',
            name='waiting_period',
            field=models.PositiveIntegerField(default=6),
        ),
    ]
