# Generated by Django 4.2.21 on 2025-05-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0011_alter_plan_lapse_period_alter_plan_waiting_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='policy_type',
            field=models.CharField(choices=[('service', 'Service Based'), ('cash', 'Cash Based')], default='service', max_length=20),
        ),
    ]
