# Generated by Django 4.2.21 on 2025-05-17 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0012_plan_policy_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='max_dependents',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='penalty_fee',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='service_fee',
        ),
        migrations.AddField(
            model_name='plan',
            name='children_allowed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='extended_allowed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='spouses_allowed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
