# Generated by Django 4.2.21 on 2025-05-17 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0002_plan_field_changes'),
        ('schemes', '0013_remove_plan_max_dependents_remove_plan_penalty_fee_and_more'),
    ]

    operations = [
    ]
