# Generated by Django 4.2.21 on 2025-05-17 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schemes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplementaryBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('premium', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('underwriter_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cover', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_ongoing', models.BooleanField(default=False)),
                ('is_laybye', models.BooleanField(default=False)),
                ('modified_user', models.EmailField(blank=True, max_length=254, null=True)),
                ('modified_date', models.DateField(auto_now=True)),
                ('scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schemes.scheme')),
            ],
        ),
    ]
