# Generated by Django 4.2.21 on 2025-05-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_diy_visible',
            field=models.BooleanField(default=True, help_text='Whether this plan is visible in the DIY application flow'),
        ),
        migrations.AddField(
            model_name='plan',
            name='terms_pdf',
            field=models.FileField(blank=True, help_text='PDF document containing terms and conditions', null=True, upload_to='plan_terms/'),
        ),
        migrations.AddField(
            model_name='plan',
            name='terms_text',
            field=models.TextField(blank=True, help_text='Terms and conditions text if no PDF is available', null=True),
        ),
    ]
