# Generated by Django 4.2.21 on 2025-05-18 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0002_plan_is_diy_visible_plan_terms_pdf_plan_terms_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('main', 'Main Member'), ('spouse', 'Spouse'), ('child', 'Child'), ('extended', 'Extended Family')], max_length=20)),
                ('age_from', models.PositiveIntegerField(default=0)),
                ('age_to', models.PositiveIntegerField(default=100)),
                ('cover_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_tiers', to='schemes.plan')),
            ],
            options={
                'verbose_name': 'Plan Tier',
                'verbose_name_plural': 'Plan Tiers',
                'ordering': ['plan', 'user_type', 'age_from'],
                'unique_together': {('plan', 'user_type', 'age_from', 'age_to')},
            },
        ),
    ]
