# Generated by Django 4.2.21 on 2025-05-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0011_remove_bank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='account_type',
            field=models.CharField(choices=[('Savings', 'Savings'), ('Current', 'Current')], default='Savings', max_length=50),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='province',
            field=models.CharField(blank=True, choices=[('EC', 'Eastern Cape'), ('FS', 'Free State'), ('GP', 'Gauteng'), ('KZN', 'KwaZulu-Natal'), ('LP', 'Limpopo'), ('MP', 'Mpumalanga'), ('NC', 'Northern Cape'), ('NW', 'North West'), ('WC', 'Western Cape')], help_text='Select the province where the scheme is located', max_length=3, null=True),
        ),
    ]
