# Generated by Django 4.2.21 on 2026-04-13 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0013_scheme_onboarding_and_wholesale_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_description', models.TextField(blank=True)),
                ('retail_premium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client_cover_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('policy_type', models.CharField(choices=[('service', 'Service Based'), ('cash', 'Cash Based')], default='service', max_length=20)),
                ('retail_below_wholesale', models.BooleanField(default=False)),
                ('wholesale_snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('onboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='schemes.branchschemeonboarding')),
                ('wholesale_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheme_products', to='schemes.plan')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
