# Generated by Django 4.2.21 on 2025-05-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_importlog_payment_created_by_payment_ip_address_and_more'),
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='payments',
            field=models.ManyToManyField(blank=True, related_name='claims', to='payments.payment'),
        ),
    ]
