# Generated by Django 4.2.21 on 2026-03-25 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        # Delete the UserRole model first (has ForeignKey to Role)
        migrations.DeleteModel(
            name='UserRole',
        ),
        # Then delete the Role model
        migrations.DeleteModel(
            name='Role',
        ),
    ]
