# Generated by Django 4.2.21 on 2025-05-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                "ALTER TABLE auth_user ADD COLUMN phone VARCHAR(20) NULL;",
                "ALTER TABLE auth_user ADD COLUMN date_of_birth DATE NULL;"
            ],
            reverse_sql=[
                "ALTER TABLE auth_user DROP COLUMN phone;",
                "ALTER TABLE auth_user DROP COLUMN date_of_birth;"
            ]
        ),
    ]
