# Generated by Django 4.2.21 on 2026-03-25 14:54

from django.db import migrations


def copy_profile_to_user(apps, schema_editor):
    """Copy all Profile data to the User model."""
    User = apps.get_model('accounts', 'User')
    Profile = apps.get_model('accounts', 'Profile')
    
    # Iterate through all profiles and copy their data to the User model
    for profile in Profile.objects.select_related('user'):
        user = profile.user
        
        # Copy profile fields to user
        user.address = profile.address or ''
        user.city = profile.city or ''
        user.state = profile.state or ''
        user.postal_code = profile.postal_code or ''
        user.country = profile.country or ''
        user.profile_picture = profile.profile_picture
        user.bio = profile.bio or ''
        user.is_verified = profile.is_verified
        user.last_activity = profile.last_activity
        
        # Save the updated user
        user.save(update_fields=[
            'address', 'city', 'state', 'postal_code', 'country',
            'profile_picture', 'bio', 'is_verified', 'last_activity'
        ])


def reverse_copy(apps, schema_editor):
    """Reverse operation - clear User profile fields (but keep user data)."""
    User = apps.get_model('accounts', 'User')
    
    # Clear the profile-related fields
    User.objects.all().update(
        address='',
        city='',
        state='',
        postal_code='',
        country='',
        profile_picture=None,
        bio='',
        is_verified=False
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_consolidate_profile_fields'),
    ]

    operations = [
        migrations.RunPython(copy_profile_to_user, reverse_copy),
    ]
