# Generated by Django 4.2.21 on 2026-03-25 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_migrate_profile_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
