# Generated by Django 4.2.21 on 2026-03-29 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0012_alter_scheme_account_type_alter_scheme_province'),
        ('branches', '0001_initial'),
        ('accounts', '0005_remove_profile_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_schemes',
            field=models.ManyToManyField(blank=True, help_text='Schemes this user can manage (for SchemeManagers).', related_name='scheme_managers', to='schemes.scheme'),
        ),
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='The branch this user is assigned to (for branch-level access control).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_users', to='branches.branch'),
        ),
    ]
