# Generated by Django 4.2.21 on 2026-04-09 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_timesta_19e18a_idx',
            old_name='audit_audit_timesta_26d309_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_user_id_292c79_idx',
            old_name='audit_audit_user_id_e1109d_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_action_86e815_idx',
            old_name='audit_audit_action_5c2f60_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_content_4c2ead_idx',
            old_name='audit_audit_content_0e8ef1_idx',
        ),
        migrations.RenameIndex(
            model_name='dataaccess',
            new_name='audit_dataa_timesta_adbd57_idx',
            old_name='audit_dataa_timesta_1f8444_idx',
        ),
        migrations.RenameIndex(
            model_name='dataaccess',
            new_name='audit_dataa_user_id_a1525d_idx',
            old_name='audit_dataa_user_id_6be8cc_idx',
        ),
        migrations.RenameIndex(
            model_name='dataaccess',
            new_name='audit_dataa_content_7b5fad_idx',
            old_name='audit_dataa_content_1dd5c6_idx',
        ),
    ]
