import csv
from django.conf import settings
from datetime import datetime

class SofWriter:
    def __init__(self, receiver_id, generation_no): ...
    def write(self, transactions, out_path): ...

class FrlWriter:
    def __init__(self, receiver_id, generation_no): ...
    def write(self, transactions, out_path): ...
