# Generated by Django 4.2.21 on 2025-05-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_policy_barcode_policy_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='document',
            field=models.FileField(blank=True, help_text='PDF policy document', null=True, upload_to='policies/'),
        ),
    ]
