# Generated by Django 4.2.21 on 2025-05-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_policy_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the policy document was emailed to the member', null=True),
        ),
    ]
