# Generated by Django 4.2.21 on 2025-05-18 07:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0003_plantier'),
        ('members', '0004_policy_email_sent_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diyapplication',
            name='cover_amount',
        ),
        migrations.RemoveField(
            model_name='diyapplication',
            name='policy_type',
        ),
        migrations.AddField(
            model_name='diyapplication',
            name='certificate_download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='diyapplication',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='diyapplication',
            name='certificate_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diyapplication',
            name='certificate_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diyapplication',
            name='certificate_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diyapplication',
            name='children_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='diyapplication',
            name='current_step',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='diyapplication',
            name='fsca_disclosure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diyapplication',
            name='has_children',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diyapplication',
            name='has_spouse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diyapplication',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diyapplication',
            name='otp_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='diyapplication',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='diyapplication',
            name='otp_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diyapplication',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diyapplication',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diyapplication',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='diyapplication',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diy_applications', to='schemes.plan'),
        ),
        migrations.AddField(
            model_name='diyapplication',
            name='popia_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diyapplication',
            name='premium_frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='diyapplication',
            name='resume_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='diyapplication',
            name='resume_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diyapplication',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diyapplication',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diyapplication',
            name='debit_day',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)]),
        ),
        migrations.AlterField(
            model_name='diyapplication',
            name='monthly_premium',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='diyapplication',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('debit_order', 'Debit Order'), ('eft', 'Electronic Funds Transfer (EFT)'), ('easypay', 'Easypay QR Code')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='diyapplication',
            name='reference_number',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='diyapplication',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('cancelled', 'Cancelled'), ('incomplete', 'Incomplete')], default='draft', max_length=20),
        ),
    ]
