# Generated by Django 4.2.21 on 2025-05-18 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_policy_lapse_warning'),
        ('members', '0005_remove_diyapplication_cover_amount_and_more'),
    ]

    operations = [
    ]
