# Generated by Django 4.2.21 on 2026-03-25 14:38

from django.db import migrations, models
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_merge_20250518_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diyapplication',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='diyapplication',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='diyapplicationdocument',
            name='application',
        ),
        migrations.RemoveField(
            model_name='diyapplicationdocument',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='diyapplicationdocument',
            name='verified_by',
        ),
        migrations.RemoveField(
            model_name='diybeneficiary',
            name='application',
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='id_number',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='ID Number'),
        ),
        migrations.AlterField(
            model_name='dependent',
            name='id_number',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='ID Number'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='member',
            name='id_number',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, db_index=True, null=True, verbose_name='ID Number'),
        ),
        migrations.AlterField(
            model_name='member',
            name='passport_number',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='Passport Number'),
        ),
        migrations.AlterField(
            model_name='member',
            name='spouse_id_number',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, verbose_name="Spouse's ID Number"),
        ),
        migrations.AlterField(
            model_name='member',
            name='spouse_passport_number',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, verbose_name="Spouse's Passport Number"),
        ),
        migrations.AlterField(
            model_name='policy',
            name='account_number',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
        migrations.DeleteModel(
            name='DIYApplicant',
        ),
        migrations.DeleteModel(
            name='DIYApplication',
        ),
        migrations.DeleteModel(
            name='DIYApplicationDocument',
        ),
        migrations.DeleteModel(
            name='DIYBeneficiary',
        ),
    ]
