# Generated by Django 4.2.21 on 2026-04-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_publicapplication_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentlink',
            name='short_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='enrollmentlink',
            name='short_url_provider',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]