# Generated by Django 4.2.21 on 2025-05-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_userrole_aiuserconsent_aisettings_airequestlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='underwriter',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this underwriter is active.'),
        ),
    ]
