# Generated by Django 4.2.21 on 2026-03-25 14:38

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0003_underwriter_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='id_number',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='passport_number',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
    ]
