# Generated by Django 4.2.21 on 2026-04-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_publicapplication_rejection_reason_and_more'),
        ('settings_app', '0004_alter_agent_id_number_alter_agent_passport_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='latest_enrollment_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, related_name='user_profiles', to='members.enrollmentlink'),
        ),
    ]